lib: [
  "_build/install/default/lib/luxe/META"
  "_build/install/default/lib/luxe/auth.ml"
  "_build/install/default/lib/luxe/dune-package"
  "_build/install/default/lib/luxe/env.ml"
  "_build/install/default/lib/luxe/luxe.a"
  "_build/install/default/lib/luxe/luxe.cma"
  "_build/install/default/lib/luxe/luxe.cmi"
  "_build/install/default/lib/luxe/luxe.cmt"
  "_build/install/default/lib/luxe/luxe.cmx"
  "_build/install/default/lib/luxe/luxe.cmxa"
  "_build/install/default/lib/luxe/luxe.ml"
  "_build/install/default/lib/luxe/luxe__Auth.cmi"
  "_build/install/default/lib/luxe/luxe__Auth.cmt"
  "_build/install/default/lib/luxe/luxe__Auth.cmx"
  "_build/install/default/lib/luxe/luxe__Env.cmi"
  "_build/install/default/lib/luxe/luxe__Env.cmt"
  "_build/install/default/lib/luxe/luxe__Env.cmx"
  "_build/install/default/lib/luxe/luxe__Server.cmi"
  "_build/install/default/lib/luxe/luxe__Server.cmt"
  "_build/install/default/lib/luxe/luxe__Server.cmx"
  "_build/install/default/lib/luxe/luxe__Start.cmi"
  "_build/install/default/lib/luxe/luxe__Start.cmt"
  "_build/install/default/lib/luxe/luxe__Start.cmx"
  "_build/install/default/lib/luxe/opam"
  "_build/install/default/lib/luxe/server.ml"
  "_build/install/default/lib/luxe/start.ml"
]
libexec: [
  "_build/install/default/lib/luxe/luxe.cmxs"
]
bin: [
  "_build/install/default/bin/luxe"
]
doc: [
  "_build/install/default/doc/luxe/README.md"
]
